version: 1.0.{build}

before_build:
- ps: nuget restore ASP.NET-MVC\ContosoUniversity\ContosoUniversity\ContosoUniversity.sln

build:
  verbosity: minimal
  project: ASP.NET-MVC\ContosoUniversity\ContosoUniversity\ContosoUniversity.sln
